# Funding options for this repository.
# Uncomment a platform and add your handle to enable the "Sponsor" button.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [abhinav-phi]
# ko-fi: [your_kofi_username]
# patreon: [your_patreon_username]
# open_collective: [your_collective_name]
# buy_me_a_coffee: [your_bmac_username]
# custom: ["https://your-link.example"]
