"""
models.py — SQLAlchemy Database Models
========================================
Defines the database tables using SQLAlchemy ORM.
Tables are created automatically on startup via Base.metadata.create_all().
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Text
from src.api.database import Base


class Alert(Base):
    """
    Stores every attack alert generated by the ML model.
    One row per detected threat.
    """
    __tablename__ = "alerts"

    id             = Column(Integer, primary_key=True, index=True)
    timestamp      = Column(DateTime, default=datetime.utcnow, index=True)
    source_ip      = Column(String(45), index=True)    # supports IPv6 (max 45 chars)
    destination_ip = Column(String(45))
    src_port       = Column(Integer,  nullable=True)
    dst_port       = Column(Integer,  nullable=True)
    prediction     = Column(String(50), index=True)    # e.g. "DDoS", "BENIGN"
    confidence     = Column(Float)                     # 0.0 – 1.0
    severity       = Column(String(20), index=True)    # NONE/LOW/MEDIUM/HIGH/CRITICAL
    shap_json      = Column(Text, nullable=True)       # JSON string of top-5 SHAP values
    true_label     = Column(String(50), nullable=True) # analyst correction (optional)

    def to_dict(self) -> dict:
        """Convert row to a plain dictionary for JSON responses."""
        return {
            "id":             self.id,
            "timestamp":      self.timestamp.isoformat() if self.timestamp else None,
            "source_ip":      self.source_ip,
            "destination_ip": self.destination_ip,
            "src_port":       self.src_port,
            "dst_port":       self.dst_port,
            "prediction":     self.prediction,
            "confidence":     round(self.confidence, 4) if self.confidence else 0.0,
            "severity":       self.severity,
            "shap_json":      self.shap_json,
            "true_label":     self.true_label,
        }